version: '3.8'
services:
  audiogen:
    image: ghcr.io/loktionov129/beep:latest
    build: .
    container_name: audiogen_gpu
    volumes:
      # - .:/app
      - ./generate_sounds.py:/app/generate_sounds.py  # Пробрасываем скрипт
      - ./presets.json:/app/presets.json              # Пробрасываем пресеты
      - ./tmp:/app/tmp                                # Папка для звуков

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
